# Generated by Django 5.0.1 on 2026-04-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='place',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес места'),
        ),
    ]
